---
- hosts: default
  become: true
  pre_tasks:
    - name: test Xen hypervisor
      slurp:
        src: /sys/hypervisor/type
      register: hypertype
      failed_when: hypertype['content'] | b64decode | trim != "xen"
  tasks:

    - include: remote.yml
    - include: libvirt.yml
    - include: rekall.yml
      when: vmi
    - include: libvmi.yml
      when: vmi
    - include: test_vm.yml
    - include: radare2.yml
    - include: r2vmi.yml
